[pytest]
markers =
    dsp: marks tests as related to the dsp module
    fit: marks tests as related to the fit module
    core: marks tests as related to the core module
    noise: marks tests as related to the noise module
    fitters: marks tests as related to the fitters module
    physics: marks tests as related to the physics module
    experiments: marks tests as related to the experiments module
    integration: marks tests as end-to-end integration tests
